### ISSUE TITLE
Doesn't compile on Windows

### ISSUE THREAD

**Issue by NyxCode** [Aurora0001/rawr#12]
**Platform: Windows 10 64-bit**
**Rust version: 1.28.0 stable**:
**rawr version: v0.1.0**

**Description of Issue:** Compilation fails 

```
Compiling idna v0.1.5
Compiling openssl-sys-extras v0.7.14
Compiling openssl v0.7.14
Compiling time v0.1.40
Compiling num-traits v0.1.43
Compiling openssl-sys v0.7.17
Compiling solicit v0.4.4
Compiling syntex_errors v0.54.0
Compiling serde_json v0.7.4
error: failed to run custom build command for `openssl v0.7.14`
process didn't exit successfully: `C:\Users\{user}\Coding\heaven-on-earth\target\debug\build\openssl-b7299ec8968f1731\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at '

Internal error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MD" "/Z7" "/W4" "/FoC:\\Users\\{user}\\Coding\\heaven-on-earth\\target\\debug\\build\\openssl-a83652704eab3099\\out\\src\\c_helpers.o" "/c" "src/c_helpers.c" with args "cl.exe" did not execute successfully (status code exit code: 2).

', C:\Users\{user}\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.54\src\lib.rs:1670:5
stack backtrace:
0: std::sys::windows::backtrace::unwind_backtrace
          at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
1: std::sys_common::backtrace::_print
          at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
2: std::sys_common::backtrace::print
          at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
3: std::panicking::default_hook::{{closure}}
          at C:\projects\rust\src\libstd\panicking.rs:211
4: std::panicking::default_hook
          at C:\projects\rust\src\libstd\panicking.rs:227
5: std::panicking::rust_panic_with_hook
          at C:\projects\rust\src\libstd\panicking.rs:511
6: std::panicking::continue_panic_fmt
          at C:\projects\rust\src\libstd\panicking.rs:426
7: std::panicking::begin_panic_fmt
          at C:\projects\rust\src\libstd\panicking.rs:413
8: gcc::fail
          at C:\Users\{user}\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.54\src\lib.rs:1670
9: gcc::Build::compile
          at C:\Users\{user}\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.54\src\lib.rs:783
10: build_script_build::main
          at .\build.rs:15
11: std::rt::lang_start::{{closure}}<()>
          at C:\projects\rust\src\libstd\rt.rs:74
12: std::rt::lang_start_internal::{{closure}}
          at C:\projects\rust\src\libstd\rt.rs:59
13: std::panicking::try::do_call<closure,i32>
          at C:\projects\rust\src\libstd\panicking.rs:310
14: panic_unwind::__rust_maybe_catch_panic
          at C:\projects\rust\src\libpanic_unwind\lib.rs:105
15: std::panicking::try
          at C:\projects\rust\src\libstd\panicking.rs:289
16: std::panic::catch_unwind
          at C:\projects\rust\src\libstd\panic.rs:392
17: std::rt::lang_start_internal
          at C:\projects\rust\src\libstd\rt.rs:58
18: std::rt::lang_start<()>
          at C:\projects\rust\src\libstd\rt.rs:74
19: main
20: invoke_main
          at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
21: __scrt_common_main_seh
          at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
22: BaseThreadInitThunk
23: RtlUserThreadStart

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `openssl-sys-extras v0.7.14`
process didn't exit successfully: `C:\Users\{user}\Coding\heaven-on-earth\target\debug\build\openssl-sys-extras-0d9df993060a29b7\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at '

Internal error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MD" "/Z7" "/W4" "/FoC:\\Users\\{user}\\Coding\\heaven-on-earth\\target\\debug\\build\\openssl-sys-extras-4f545acfe8d1f958\\out\\src\\openssl_shim.o" "/c" "src/openssl_shim.c" with args "cl.exe" did not execute successfully (status code exit code: 2).

', C:\Users\{user}\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.54\src\lib.rs:1670:5
stack backtrace:
0: std::sys::windows::backtrace::unwind_backtrace
          at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
1: std::sys_common::backtrace::_print
          at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
2: std::sys_common::backtrace::print
          at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
3: std::panicking::default_hook::{{closure}}
          at C:\projects\rust\src\libstd\panicking.rs:211
4: std::panicking::default_hook
          at C:\projects\rust\src\libstd\panicking.rs:227
5: std::panicking::rust_panic_with_hook
          at C:\projects\rust\src\libstd\panicking.rs:511
6: std::panicking::continue_panic_fmt
          at C:\projects\rust\src\libstd\panicking.rs:426
7: std::panicking::begin_panic_fmt
          at C:\projects\rust\src\libstd\panicking.rs:413
8: gcc::fail
          at C:\Users\{user}\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.54\src\lib.rs:1670
9: gcc::Build::compile
          at C:\Users\{user}\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.54\src\lib.rs:783
10: build_script_build::main
          at .\build.rs:19
11: std::rt::lang_start::{{closure}}<()>
          at C:\projects\rust\src\libstd\rt.rs:74
12: std::rt::lang_start_internal::{{closure}}
          at C:\projects\rust\src\libstd\rt.rs:59
13: std::panicking::try::do_call<closure,i32>
          at C:\projects\rust\src\libstd\panicking.rs:310
14: panic_unwind::__rust_maybe_catch_panic
          at C:\projects\rust\src\libpanic_unwind\lib.rs:105
15: std::panicking::try
          at C:\projects\rust\src\libstd\panicking.rs:289
16: std::panic::catch_unwind
          at C:\projects\rust\src\libstd\panic.rs:392
17: std::rt::lang_start_internal
          at C:\projects\rust\src\libstd\rt.rs:58
18: std::rt::lang_start<()>
          at C:\projects\rust\src\libstd\rt.rs:74
19: main
20: invoke_main
          at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
21: __scrt_common_main_seh
          at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
22: BaseThreadInitThunk
23: RtlUserThreadStart

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Steps to reproduce**
1. Add rawr to Cargo.toml
2. (Try to) compile

**Comment by johan-bjareholt** [comment]
Found this issue right after writing a related issue:

https://github.com/Aurora0001/rawr/issues/13

This is the reason why it doesn't compile, I don't have a solution for it though.

**Comment by botahamec** [comment]
I don't know if you still need this, but I'll leave it for anyone who does.

This crate is actually very out of date. It relies on a heavily out-of-date version of the hyper crate, which fails to compile on newer machines. The last update to this repository was three years ago. There's been a pull request which fixes the issue, but it hasn't been implemented.

I fixed many of the issues by pulling the contributions of others into my own fork. Simply change your Cargo.toml in the following way:

Before:
```
[dependencies]
rawr = "0.1"
```

After:
```
[dependencies]
rawr = {git = "https://github.com/Botahamec/rawr.git", branch = "master"}
```

You don't need to change anything else in your project. Everything should work as intended,
